from rest_framework import generics, permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.db.models import Q
from django.urls import reverse
from .models import Entry, Visibility, Comment
from authors.models import FollowRequestStatus
from authors.serializers import AuthorSerializer
from .serializers import EntrySerializer, CommentSerializer

class PublicEntriesListView(generics.ListAPIView):
    serializer_class = EntrySerializer
    permission_classes = [permissions.AllowAny]

    def get_queryset(self):
        return Entry.objects.filter(visibility=Visibility.PUBLIC)\
                            .select_related("author")\
                            .order_by("-published")

class EntryDetailView(generics.RetrieveUpdateDestroyAPIView):
    """
    GET /api/entries/<uuid:entry_id>/
    Returns a single entry if visible to the requester.
    """
    permission_classes = [permissions.AllowAny]

    def get_object(self, entry_id):
        """
        Retrieves the entry object from the database and returns it unless incorrect visibility
        """
        entry = get_object_or_404(Entry, id=entry_id)
        
        # Deleted entries hidden from those who arent admin
        if entry.visibility == "DELETED":
            raise Http404("Entry not found")

        # Only show friends-only posts to friends
        if entry.visibility == Visibility.FRIENDS and (
            not self.request.user.is_authenticated or entry.author != self.request.user and
            # generated by Github Copilot on 2025-10-20
            not entry.author.follow_requests_sent.filter(
                followee=self.request.user, status=FollowRequestStatus.APPROVED
            ).exists()
        ):
            raise Http404("Entry not found")

        return entry

    def get(self, request, entry_id):
        """
        Handles GET requests for a single entry by ID.
        Returns the serialized entry in the response body.
        """
        entry = self.get_object(entry_id)
        serializer = EntrySerializer(entry, context={"request": request})
        return Response(serializer.data)


class MyEntriesListView(generics.ListCreateAPIView):
    """
    GET /api/author/<uuid:author_id>/entries/
    POST /api/author/<uuid:author_id>/entries/
    """
    serializer_class = EntrySerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        """
        Returns list of current users entries excluding deleted entries
        """
        return Entry.objects.filter(author=self.request.user).exclude(visibility="DELETED").order_by("-published")

    def perform_create(self, serializer):
        """
        Saves an entry with the current user as the author
        Called wjen a POST request is made to the view.
        """
        serializer.save(author=self.request.user)

    def list(self, request, *args, **kwargs):
        """
        Serializes queryset when GET response is received
        Returns 200 OK response with serialized queryset as body 
        """
        queryset = self.get_queryset()
        serializer = self.get_serializer(queryset, many=True, context={"request": request})
        return Response({
            "type": "entries",
            "src": serializer.data
        })
    
class EntryEditDeleteView(generics.RetrieveUpdateDestroyAPIView):
    """
    GET / PUT / DELETE /api/entries/<uuid:entry_id>/edit/
    Only the author can edit or delete their entry.
    """
    serializer_class = EntrySerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_object(self):
        entry_id = self.kwargs.get("entry_id")
        entry = get_object_or_404(Entry, id=entry_id, author=self.request.user)
        
        # Prevent editing deleted entries
        if entry.visibility == "DELETED":
            raise Http404("Entry not found")

        return entry
    
class EntryLikesListView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request, entry_id):
        entry = get_object_or_404(Entry, id=entry_id)
        if not entry.can_view(request.user):
            raise Http404

        # Pagination parameters 
        page = max(1, int(request.query_params.get("page", 1)))
        size = max(1, int(request.query_params.get("size", 5)))
        start = (page - 1) * size
        end = start + size

        likes_qs = entry.liked_by.all()
        likes_page = likes_qs[start:end]

        likes_api_url = request.build_absolute_uri(
            reverse("api:entry-likes", args=[entry.id])
        )
        entry_html_url = request.build_absolute_uri(
            reverse("entries:view_entry", args=[entry.id])
        )

        src = []
        for author in likes_page:
            src.append(
                {
                    "type": "like",
                    "author": AuthorSerializer(
                        author, context={"request": request}
                    ).data,
                    "published": entry.updated,
                    "id": f"{likes_api_url}{author.id}/",
                    "object": entry_html_url,
                }
            )

        return Response(
            {
                "type": "likes",
                "web": entry_html_url,
                "id": likes_api_url,
                "page_number": page,
                "size": size,
                "count": likes_qs.count(),
                "src": src,
            }
        )



class EntryCommentsListCreateView(generics.ListCreateAPIView):
    """
    GET /api/entries/<entry_id>/comments/
    POST /api/entries/<entry_id>/comments/
    """

    serializer_class = CommentSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    _entry = None

    def get_entry(self):
        if self._entry is not None:
            return self._entry
        entry = get_object_or_404(Entry, id=self.kwargs["entry_id"])
        if not entry.can_view(self.request.user):
            raise Http404("Entry not found")
        self._entry = entry
        return entry

    def get_queryset(self):
        entry = self.get_entry()
        comments = entry.comments.select_related("author")
        if (
            entry.visibility == Visibility.FRIENDS
            and self.request.user.is_authenticated
            and self.request.user != entry.author
        ):
            comments = comments.filter(author__in=[self.request.user, entry.author])
        return comments.order_by("created_at")

    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serializer = self.get_serializer(queryset, many=True, context=self.get_serializer_context())
        entry_url = request.build_absolute_uri(
            reverse("api:entry-detail", args=[self.get_entry().id])
        )
        return Response({
            "type": "comments",
            "entry": entry_url,
            "comments": serializer.data,
        })

    def perform_create(self, serializer):
        entry = self.get_entry()
        if not self.request.user.is_authenticated:
            raise Http404("Entry not found")
        serializer.save(entry=entry, author=self.request.user)


class CommentDetailView(generics.RetrieveAPIView):
    """
    GET /api/comments/<comment_id>/
    """

    serializer_class = CommentSerializer
    permission_classes = [permissions.AllowAny]

    def get_object(self):
        comment = get_object_or_404(
            Comment.objects.select_related("entry", "author"),
            id=self.kwargs["comment_id"],
        )
        entry = comment.entry
        if not entry.can_view(self.request.user):
            raise Http404("Comment not found")
        if (
            entry.visibility == Visibility.FRIENDS
            and self.request.user != entry.author
            and self.request.user != comment.author
        ):
            raise Http404("Comment not found")
        return comment


class CommentLikeView(APIView):
    """
    POST /api/comments/<comment_id>/like/
    """

    permission_classes = [permissions.IsAuthenticated]

    def post(self, request, comment_id):
        comment = get_object_or_404(
            Comment.objects.select_related("entry"),
            id=comment_id,
        )
        entry = comment.entry
        if not entry.can_view(request.user):
            raise Http404("Comment not found")
        if (
            entry.visibility == Visibility.FRIENDS
            and request.user not in {entry.author, comment.author}
        ):
            raise Http404("Comment not found")

        comment.liked_by.add(request.user)
        serializer = CommentSerializer(comment, context={"request": request})
        return Response(serializer.data, status=status.HTTP_200_OK)
