# Generated by Django 5.2.6 on 2025-10-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_entry_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('image/png;base64', 'PNG Image'), ('image/jpeg;base64', 'JPEG Image')], default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends only'), ('DELTED', 'Deleted')], default='PUBLIC', max_length=10),
        ),
    ]
