# Generated by Django 5.2.6 on 2025-10-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_content_type_alter_entry_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends only'), ('DELTED', 'Deleted'), ('UNLISTED', 'Unlisted')], default='PUBLIC', max_length=10),
        ),
    ]
