# Generated by Django 5.2.6 on 2025-10-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entry_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
