# Generated by Django 5.2.6 on 2025-11-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_alter_remotenode_password_alter_remotenode_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotenode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
