# Generated by Django 5.2.6 on 2025-11-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_remotenode_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotenode',
            name='base_url',
            field=models.URLField(help_text='e.g., https://team-dodgerblue.herokuapp.com'),
        ),
    ]
