# Generated by Django 5.2.6 on 2025-11-17 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_alter_entry_content_type'),
        ('entries', '0013_alter_remotenode_base_url'),
    ]

    operations = [
    ]
