"""
Django settings for socialdistribution project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^0bws-#z@jo5(653=2axk0r+6@42%9$#%4s$gse^g+!+2xqkcx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "1") == "1"
ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    # local apps
    'entries',
    'authors',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',  # serves Swagger UI/Redoc assets
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'socialdistribution.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'socialdistribution.wsgi.application'

if os.environ.get("DATABASE_URL") is not None:
    # Running on Heroku / with a real DATABASE_URL
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    # Running locally: use SQLite with no sslmode
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static & media
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles" 

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'authors.Author'

# Auth redirects
LOGIN_REDIRECT_URL = 'stream'
LOGOUT_REDIRECT_URL = 'authors:login'
LOGIN_URL = 'authors:login'

# DRF config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'socialdistribution.authentication.RemoteNodeBasicAuthentication', # Checks for the remote nodes first
        'rest_framework.authentication.SessionAuthentication',         # Then checks for local user sessions
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'socialdistribution.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 10,

    # OpenAPI generator
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular (OpenAPI/Swagger)
# Note: SECURITY = [] means the schema does not require auth globally,
# keeping the Swagger "Authorize" dialog out of the way for most operations.
SPECTACULAR_SETTINGS = {
    'TITLE': 'SocialDistribution API',
    'DESCRIPTION': 'OpenAPI schema for the SocialDistribution project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [],  # do not advertise global auth in docs (endpoints can still enforce auth)
}

# Cron
CRONJOBS = [
    ('*/60 * * * *', 'django.core.management.call_command', ['sync_github']),
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Allowed hosts and CSRF trusted origins from environment dynamically
_APP_DOMAINS = [h.strip() for h in os.getenv("APP_DOMAINS", "").split(",") if h.strip()]
if _APP_DOMAINS:
    ALLOWED_HOSTS = _APP_DOMAINS
CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in _APP_DOMAINS]

# For authenticating to remote nodes (example node credentials)
OUR_NODE_USERNAME = "1234"
OUR_NODE_PASSWORD = "1234"