# Generated by Django 5.2.6 on 2025-11-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, null=True),
        ),
    ]
